stages:
  - build
  - publish


build:
  stage: build
  tags:
    - pypi
  script:
    - python setup.py bdist_wheel
  artifacts:
    when: on_success
    paths:
      - dist/*


publish:
  stage: publish
  tags:
    - pypi
  script:
    - VERSION=$(python setup.py -V)
    - PKG=$(python setup.py --name)
    - rm -rf /var/www/pypi/loyaltyengine_utils
    - rm -rf /var/www/pypi/loyaltyengine-utils
    - pypi-private -v publish $PKG $VERSION
